#!/bin/bash -e

[[ $DEBUG -gt 0 ]] && set -x || set +x

BASE_DIR="$(cd "$(dirname "$0")"; pwd)"
PROGNAME=${0##*/}

usage () {
    printf "Setup Elasticsearch on AWS EC2 instance.\n\n"

    printf "$PROGNAME\n"
    printf "\t[-n CLUSTER_NAME]\n"
    printf "\t[-p PLUGIN_NAME] ...\n"
    printf "\t[-s CLUSTER_SETTING] ...\n"
    printf "\t[-l public | private | localhost]\n"
    printf "\t[-o PORT]\n"
    printf "\t[-h]\n\n"

    printf "OPTIONS\n"
    printf "\t[-n CLUSTER_NAME]\n\n"
    printf "\tCluster name. Default is 'esonaws'.\n\n"

    printf "\t[-p PLUGIN_NAME] ...\n\n"
    printf "\tInstall specified plugin.\n"
    printf "\tMulti -p is allowed.\n\n"

    printf "\t[-s CLUSTER_SETTING] ...\n\n"
    printf "\tCLUSTER_SETTING format: key=value\n"
    printf "\tMulti -s is allowed.\n\n"

    printf "\t[-l public | private | localhost]\n\n"
    printf "\tNetwork interface to listen on. Default is 'private' IP.\n\n"

    printf "\t[-o port]\n\n"
    printf "\tPort to listen on. Default port is 9200.\n\n"

    printf "\t[-h]\n\n"
    printf "\tThis help.\n\n"
    exit 255
}

plugin_is_exist () {
    local name=${1:?}
    /usr/share/elasticsearch/bin/elasticsearch-plugin list | grep -w "$name" > /dev/null
}

install_plugin () {
    local name=${1:?}

    if plugin_is_exist "$name"; then
        echo "plugin $name already installed"
    else
        /usr/share/elasticsearch/bin/elasticsearch-plugin install -b "$name"
    fi
}

get_ec2_private_ip () {
    curl http://169.254.169.254/latest/meta-data/local-ipv4
}

get_ec2_public_ip () {
    curl http://169.254.169.254/latest/meta-data/public-ipv4
}

get_total_memory_size () {
    cat /proc/meminfo | \
        grep MemTotal | \
        awk '{ print $2 }' # In KB
}

calc_es_heap_size () {
    local mem=$(get_total_memory_size)
    echo $((mem / 1024 / 2))m # In MB
}


cluster_name='esonaws'
plugins=()
settings=()
listen='private'
port=9200

while getopts n:p:s:l:o:h opt; do
    case $opt in
        n)
            cluster_name=$OPTARG
            ;;
        p)
            plugins[${#plugins[@]}]=$OPTARG
            ;;
        s)
            settings[${#settings[@]}]=$OPTARG
            ;;
        l)
            listen=$OPTARG
            ;;
        o)
            port=$OPTARG
            ;;
        h|*)
            usage
            ;;
    esac
done

# plugins

for p in "${plugins[@]}"; do
    install_plugin "$p"
done

# elasticsearch settings

content="ES_HEAP_SIZE=$(calc_es_heap_size)"
regex='^#ES_HEAP_SIZE='
mark_begin="# BEGIN: Generated by $PROGNAME for ES_HEAP_SIZE"
mark_end="# -END-: Generated by $PROGNAME for ES_HEAP_SIZE"
sh "$BASE_DIR/inject-to-file.sh" \
    -c "$content" \
    -f /etc/sysconfig/elasticsearch \
    -p after \
    -a "$regex" \
    -m "$mark_begin" \
    -n "$mark_end" \
    -x "$mark_begin" \
    -y "$mark_end"

content='MAX_LOCKED_MEMORY=unlimited'
regex='^#MAX_LOCKED_MEMORY='
mark_begin="# BEGIN: Generated by $PROGNAME for MAX_LOCKED_MEMORY"
mark_end="# -END-: Generated by $PROGNAME for MAX_LOCKED_MEMORY"
sh "$BASE_DIR/inject-to-file.sh" \
    -c "$content" \
    -f /etc/sysconfig/elasticsearch \
    -p after \
    -a "$regex" \
    -m "$mark_begin" \
    -n "$mark_end" \
    -x "$mark_begin" \
    -y "$mark_end"

# cluster basic settings

case $listen in
    private)
        ip=$(get_ec2_private_ip)
        ;;
    public)
        ip=$(get_ec2_public_ip)
        ;;
    localhost)
        ip='127.0.0.1'
        ;;
esac

content="
cluster.name: \"$cluster_name\"
network.host: [\"${ip:?}\"]
"
mark_begin="# BEGIN: Generated by $PROGNAME for basic cluster settings"
mark_end="# -END-: Generated by $PROGNAME for basic cluster settings"
sh "$BASE_DIR/inject-to-file.sh" \
    -c "$content" \
    -f /etc/elasticsearch/elasticsearch.yml \
    -p end \
    -m "$mark_begin" \
    -n "$mark_end" \
    -x "$mark_begin" \
    -y "$mark_end"

# cluster parameterize settings

for kv in "${settings[@]}"; do
    key="$(echo "$kv" | cut -d= -f1)"
    content="$(echo "$kv" | sed 's/=/: /')"
    mark_begin="# BEGIN: Generated by $PROGNAME for $key"
    mark_end="# -END-: Generated by $PROGNAME for $key"
    sh "$BASE_DIR/inject-to-file.sh" \
       -c "$content" \
       -f /etc/elasticsearch/elasticsearch.yml \
       -p end \
       -m "$mark_begin" \
       -n "$mark_end" \
       -x "$mark_begin" \
       -y "$mark_end"
done

service elasticsearch start
chkconfig --add elasticsearch

exit
